### ISSUE TITLE
First use (Windows)

### ISSUE THREAD

**Issue by p0nce** [kassane/ldcup#1]
- Basically it needs `7z` in PATH
 > '7z' n’est pas reconnu en tant que commande interne

- After I fixed that and install ldc-latest, it doesn't say where is the compiler.
![image](https://github.com/user-attachments/assets/0a4e7c27-413c-449d-a64f-b03388af7d3e)
    1. How to find that path of install?
    2. Do I need to put LDC in PATH?

**Comment by kassane** [comment]
For windows, the default directory is `%LOCALAPPDATA%\dlang`.
Like, https://github.com/kassane/ldcup/actions/runs/12436508995/job/34724839939#step:5:3459
https://github.com/kassane/ldcup/blob/c48d581a34bc6edb0b4ce7748d51ace593ba39f7/source/impl.d#L57-L65

Or, try `ldcup install --instal-dir=customPath`.

And to add in system PATH (powershell):
https://github.com/kassane/ldcup/blob/c48d581a34bc6edb0b4ce7748d51ace593ba39f7/source/impl.d#L153-L159

**Comment by kassane** [comment]
> And to add in system PATH (powershell):
> 
> https://github.com/kassane/ldcup/blob/c48d581a34bc6edb0b4ce7748d51ace593ba39f7/source/impl.d#L153-L159

This is only happening in version 1.0.2. Previous releases would create batch scripts to call ldc2. https://github.com/kassane/ldcup/commit/86c63a311b81be7d250698dbfc01ae4294711ae9

**Comment by p0nce** [comment]
Thanks. I have read the source. I meant that users of ldcup are going to ask themselves those questions, and I think the software could tell upon installing.

**Comment by kassane** [comment]
> I think the software could tell upon installing.

I admit that some information was hidden in the latest version, even installing in verbose mode.

For example there are some `writeln` omitted exclusively for debugging (displaying the detected shell for posix and rootpath during installation).

Any ideas/suggestions you have PR will be welcome.

**Comment by kassane** [comment]
https://github.com/kassane/ldcup/releases/tag/v1.0.3

This new release version, show `installing to $(compilerPath)` and add `ldcup run -- <ldc2-flags>`
